nherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

# =================
# Style Cops
# =================
Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 1


Style/NumericLiterals:
  Enabled: true

Style/Documentation:
  Enabled: true

# =================
# Layout Cops
# =================
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# =================
# RSpec Cops
# =================
RSpec/Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/*'
    - 'spec/features/**/*'

# =================
# Rails Cops
# =================

# This needed to be disabled to to some kind of parsing error happening within
# Rubocop. However, this is something to be revisited as it would be important to
# have verification for indexes on unique values in database columns
Rails/UniqueValidationWithoutIndex:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
    <% end %>
