name: RubyCI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  # Add secret key to Repository secrets
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
  REDIS_URL: redis://localhost:6379/0

jobs:
  tests:
    name: Tests
    env:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      - name: Create DB
        run: |
          bin/rails db:create
      - name: Create postgis extension
        run: |
          psql -h localhost -d postgres -U postgres -c '\c test; CREATE EXTENSION postgis;'
        env:
          PGPASSWORD: postgres
      - name: Run migrations
        run: |
          bin/rails db:migrate
      - name: Install Node packages
        run: |
          bin/yarn install
      - name: Run tests
        run: |
          bundle exec rspec --fail-fast

  security:
    name: Security
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run security checks
        run: |
          bundle exec brakeman -w3 -o tmp/brakeman.html
