name: RubyCI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  # Add secret key to Repository secrets
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
  REDIS_URL: redis://localhost:6379/0

jobs:
  postgres:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      env:
        PGPASSWORD: postgres_password
